sudo: required

language: cpp

services:
  - docker
  
before_install:
- docker pull matisyo/jobify-docker:latest
- docker run -d -p 127.0.0.1:80:4567 matisyo/jobify-docker /bin/sh -c "cd /home/travis; rm -rf Jobify; ./installer_ducker.sh;"
- docker ps -a

