sudo: required

language: cpp

services:
  - docker
 
before_install:
  - docker build -t jobifiando .
  - docker images 
  
script:
  - docker run --name jovifier -d -p 8000:8000 jobifiando;
  - docker ps -l
